/*
 * StaffFrame.java
 *
 * Created on Dec 18, 2009, 2:13:48 PM
 * @author Matthew Scott
 * @version $Id: StaffFrame.java 4 2010-02-02 23:14:49Z mjs@mjs-svc.com $
 */

package com.mjs_svc.lywriter.app;

import com.mjs_svc.lywriter.api.*;

/**
 *
 * @author Matthew Scott
 * @version $Id: StaffFrame.java 4 2010-02-02 23:14:49Z mjs@mjs-svc.com $
 */
public class StaffFrame extends javax.swing.JInternalFrame {

    /** Creates new form StaffFrame */
    public StaffFrame(Staff staff) {
        initComponents();

        splitPane.setTopComponent(new RollPanel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        editorScroller = new javax.swing.JScrollPane();
        editorArea = new javax.swing.JTextArea();

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        editorArea.setColumns(20);
        editorArea.setRows(5);
        editorScroller.setViewportView(editorArea);

        splitPane.setBottomComponent(editorScroller);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea editorArea;
    private javax.swing.JScrollPane editorScroller;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

}
